language: go
go_import_path: github.com/crunchydata/crunchy-proxy
install: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -y swig3.0
  - sudo ln -s /usr/bin/swig3.0 /usr/local/bin/swig
services:
  - postgresql
go:
  - 1.10.x
  - master
script:
  - 'make ${JOB}'
env:
  global:
    - GOARCH=amd64
  matrix:
    - JOB=lint
    - JOB=test
    - JOB=race
    - JOB=default
jobs:
  fast_finish: true
after_success:
  - bash <(curl -s https://codecov.io/bash)