server:
  proxy:
    hostport: 0.0.0.0:5432
  admin:
    hostport: 127.0.0.1:8000

nodes:
  master:
    hostport: 172.17.0.4:5432
    role: master
    metadata: {}
  
credentials:
  username: postgres
  database: teste
  password: mysecretpassword
  options:
  ssl:
    enable: false
    sslmode: disable

pool:
  capacity: 2

healthcheck:
  delay: 60
  query: select now();
