server:
  proxy:
    hostport: 0.0.0.0:5433
  admin:
    hostport: 127.0.0.1:8000

nodes:
  master:
    hostport: 127.0.0.1:5432
    role: master
    metadata: {}
  
credentials:
  username: postgres
  database: postgres
  password: 
  options:
  ssl:
    enable: false
    sslmode: disable

pool:
  capacity: 2

healthcheck:
  delay: 60
  query: select now();
